// export const ADD_VEHICLE_DETAILS_SUCCESS = "ADD_VEHICLE_DETAILS_SUCCESS";
// export const ADD_VEHICLE_DETAILS_REQUEST = "ADD_VEHICLE_DETAILS_REQUEST";
// export const ADD_VEHICLE_DETAILS_FAILURE = "ADD_VEHICLE_DETAILS_FAILURE";

export const GET_VEHICLE_DETAILS_SUCCESS = "GET_VEHICLE_DETAILS_SUCCESS";
export const GET_VEHICLE_DETAILS_REQUEST = "GET_VEHICLE_DETAILS_REQUEST";
export const GET_VEHICLE_DETAILS_FAILURE = "GET_VEHICLE_DETAILS_FAILURE";
