// export const ADD_VEHICLE_DETAILS_SUCCESS = "ADD_VEHICLE_DETAILS_SUCCESS";
// export const ADD_VEHICLE_DETAILS_REQUEST = "ADD_VEHICLE_DETAILS_REQUEST";
// export const ADD_VEHICLE_DETAILS_FAILURE = "ADD_VEHICLE_DETAILS_FAILURE";

export const ADD_FILTER_DETAILS = "ADD_FILTER_DETAILS";
export const ADD_DATE_DETAILS = "ADD_DATE_DETAILS";
export const ADD_VEHICLE_TYPE = "ADD_VEHICLE_TYPE";
export const ADD_VEHICLE_DETAILS = "ADD_VEHICLE_DETAILS";

export const GET_VEHICLE_DETAILS_SUCCESS = "GET_VEHICLE_DETAILS_SUCCESS";
export const GET_VEHICLE_DETAILS_REQUEST = "GET_VEHICLE_DETAILS_REQUEST";
export const GET_VEHICLE_DETAILS_FAILURE = "GET_VEHICLE_DETAILS_FAILURE";
